// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var GraqlLexer = require("./GraqlLexer");
var GraqlParser = require("./GraqlParser");
var GraqlVisitor = require("./GraqlVisitor");

var InputStream = { };

function make(prim) {
  return new GraqlLexer.GraqlLexer(prim);
}

var Lexer = {
  make: make
};

var CommonTokenStream = { };

function make$1(prim) {
  return new GraqlParser.GraqlParser(prim);
}

var Parser = {
  make: make$1
};

function make$2(prim) {
  return new GraqlVisitor.GraqlVisitor(prim);
}

var Visitor = {
  make: make$2
};

exports.InputStream = InputStream;
exports.Lexer = Lexer;
exports.CommonTokenStream = CommonTokenStream;
exports.Parser = Parser;
exports.Visitor = Visitor;
/* ./GraqlLexer Not a pure module */
