// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Antlr4 = require("antlr4");
var Antlr4$ReactHooksTemplate = require("./Antlr4.bs.js");

var input = "define vehicle sub entity;";

var chars = new Antlr4.InputStream(input);

var lexer = Antlr4$ReactHooksTemplate.Lexer.make(chars);

var tokens = new Antlr4.CommonTokenStream(lexer);

var parser = Antlr4$ReactHooksTemplate.Parser.make(tokens);

var visitor = Antlr4$ReactHooksTemplate.Visitor.make(/* () */0);

var tree = parser.query(/* () */0);

console.log(tree);

exports.input = input;
exports.chars = chars;
exports.lexer = lexer;
exports.tokens = tokens;
exports.parser = parser;
exports.visitor = visitor;
exports.tree = tree;
/* chars Not a pure module */
