// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Luxon = require("luxon");

var myDate = Luxon.DateTime.local().setZone("America/New_York").minus({
      weeks: 1
    });

console.log(myDate);

exports.myDate = myDate;
/* myDate Not a pure module */
